SELECT * FROM walmartdata.sales;
use walmartdata;
select * from walmartdata.sales where branch = "A";
select * from walmartdata.sales where branch = "";
select * from walmartdata.sales where city = "Naypyitaw" and gender = "male";
select * from walmartdata.sales where city = "Yangon" or payment = "cash";
select * from walmartdata.sales where not branch = "B";
describe sales;
select * from sales where quantity between 5 and 7 order by quantity asc;
select * FROM walmartdata.sales;
select max(quantity) as max_qnt from sales;
select min(rating) as min_rating from sales;
select round(avg(rating),2) as avg_rating from sales;
select sum(total) as sum_total from sales;
select round(avg(unit_price),2) as avg_price from sales;
select * FROM walmartdata.sales;
select date(date),month(date), dayofmonth(date) from sales;
select dayofmonth(date) from sales;
select dayname(date) from sales;
select dayofweek(date) from sales;
select dayofyear(date) from sales;
select day(date) from sales;
SELECT YEAR(date), MONTH(date),monthname(date) FROM sales;
select month(date) from sales;
select monthname(date) from sales;
select * FROM walmartdata.sales;
select count(invoice_id) from sales;
select count(distinct(rating)) from sales;
select concat(city," - ",branch, " - ", gender) as address from sales;
select concat_ws(" - ",customer_type,product_line,payment) as customer_info from sales;
select length(gender) from sales;
select * FROM walmartdata.sales;
select left(gender,1) as Gender from sales;
select right(customer_type,4) as C_type from sales;
select mid(customer_type,2,3) as C_type from sales;
select * from sales where invoice_id like "%78%";
select * from sales where payment like "C%";
select * from sales where product_line like "%y";
select * FROM walmartdata.sales where product_line in ("Sports and travel");
select * FROM walmartdata.sales where product_line not in ("Sports and travel");
select * FROM walmartdata.sales order by total desc limit 10;
select gender, count(*) as total_members FROM walmartdata.sales group by gender;
select * from sales  limit 15 offset 6;
select * from sales;